### ISSUE TITLE
support for mongodb

### ISSUE THREAD

**Issue by jagdishjadeja** [casejs/case#24]
need support for mongodb

**Comment by SebConejo** [comment]
Hello @jagdishjadeja , We close this issue because we just deployed a new version of CASE. This version is totally different from the V1. If you still need support, please create a new issue for that. 

Thank you

**Comment by jagdishjadeja** [comment]
Does it support mongodb ?

**Comment by brunobuddy** [comment]
Hello @jagdishjadeja,

Not yet, only SQL databases at the moment.

**Comment by dotku** [comment]
will you support Postgres?

**Comment by SebConejo** [comment]
Hi @dotku,

For now, CASE only works with SQLite. Allowing work with Postgres depends on feedback we will receive. The most frequent or upvoted feedback will be prioritized. Don't hesitate to send us your feedback here: https://github.com/casejs/CASE/discussions/categories/feedback.
