### ISSUE TITLE
Non Functional Link 

### ISSUE THREAD

**Issue by SubstantialCattle5** [casejs/CASE#62]
**Describe the bug**
Due to a spelling mistake the link given in the comments of entities was not working.

**To Reproduce**
1. Create an entity
2. Click on the link available in the comment
3. See error

**Expected behavior**
The link should be functional

**Screenshots**
The link redirects to this page -> 
![image](https://github.com/casejs/CASE/assets/92233871/88d05676-0455-4c45-9011-afa9c440fda3)

**Environment (please give information about your environment):**
 - OS:Pop OS
 - Browser  firefox

**Code snippets**
If possible, show extracts from your code to help us better understand the issuse.
```ts
import { CaseEntity, Entity, Prop, PropType } from '@casejs/case'

@Entity({
  nameSingular: 'cat',
  namePlural: 'cats',
  propIdentifier: 'name',
  slug: 'cats',
})
export class Cat extends CaseEntity {
  @Prop({
    type: PropType.Text
  })
  name: string

  // Learn more about CASE Entities and how to add properties here: https://docs.case.app/properites
}

```

**Comment by brunobuddy** [comment]
Thank for your work @SubstantialCattle5, it's deployed :tada:
