### ISSUE TITLE
ERROR in authentification : secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by ismaelguerrib** [casejs/CASE#79]
**To Reproduce**
- Use case starter as template
- follow the README.me and seed 
- add a .env with a variable JWT_secret
- try to authentificate
- the error occurs

**Expected behavior**
I want to authentificate

**Screenshots**
When I try to auth I have an internal error server that said : 
<img width="804" alt="Capture d’écran 2023-10-02 à 16 21 20" src="https://github.com/casejs/CASE/assets/50170060/3d5fcb79-5fe5-4ebe-8498-93b7d7959e95">

**Additional context**
I add a .env with a JWT_SECRET but the error still occurs. 
This article talk about it : https://dev.to/emmanuelthecoder/how-to-solve-secretorprivatekey-must-have-a-value-in-nodejs-4mpg

**Comment by brunobuddy** [comment]
@ismaelguerrib CASE Starter is not supposed to be used as a template.

You can look at [CASE docs](https://docs.case.app/install) and follow the install process.
