### ISSUE TITLE
Image from seed is not displayed

### ISSUE THREAD

**Issue by ismaelguerrib** [casejs/CASE#80]
**Describe the bug**
Image from seed is not display. 

When the url is from internet the image dont appears like (  https://loremflickr.com/cache/resized/65535_52681423932_b83a98e6f8_b_640_480_nofilter.jpg ) 

**To Reproduce**
- Follow the doc of case to adde a image property https://docs.case.app/property-types?id=image
- Add a seed to the image property like it should be added 
```
  @Prop({
    type: PropType.Image,
    seed: () => faker.image.urlLoremFlickr({ category: 'cats' }),
  })
  image: string;
```
**Expected behavior**
The image should be displayed

**Screenshots**
![Capture d’écran 2023-10-03 à 09 28 37](https://github.com/casejs/CASE/assets/50170060/832fcfa2-79e2-4c03-9da8-dff617c73440)

![Capture d’écran 2023-10-03 à 09 18 29](https://github.com/casejs/CASE/assets/50170060/54dce4e6-ad72-4e8f-a4cc-ecfa1c643980)

**Additional context**
When we add an image by the create edit, the bug dont occurs.

**Comment by brunobuddy** [comment]
@ismaelguerrib @SebConejo 

The [image yield](https://docs.case.app/property-types?id=image) refers to images that are managed by CASE and stored in the app storage.

We do not have any yield for external images yet. Do you think that it can be useful ?
