### ISSUE TITLE
Can't build the case/server package

### ISSUE THREAD

**Issue by shavidze** [casejs/CASE#84]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/casejs/CASE/blob/master/packages/case/README.md'
When I run 
```bash
npm run build 
```
getting the error 

```js
Error: Cannot find module 'webpack'
```
**Environment (please give information about your environment):**
 - OS: [iOS]

**Comment by brunobuddy** [comment]
@shavidze you have to install dependencies before the build:

```
npm install
npm run build
```

I updated the README, thanks for creating that issue :+1:

**Comment by shavidze** [comment]
> @shavidze you have to install dependencies before the build:
> 
> ```
> npm install
> npm run build
> ```
> 
> I updated the README, thanks for creating that issue 👍

Sure I run `npm install` before run build, I didn't work and it does not work for now for me 🤔
