### ISSUE TITLE
Login page displays credentials to log even if DB is empty

### ISSUE THREAD

**Issue by brunobuddy** [casejs/CASE#85]
## Description

When cloning an existing CASE repository (**not using** `npx create-case-app` as this script seeds the DB), the login page says that I can connect with `user1@case.app`.

This sentence appears even if my DB is empty and thus prompts users to login even if they can't.

## How to reproduce ?

- The quickest way to simulate an existing CASE project is to go to the [starter repo](https://github.com/casejs/case-starter) and click on Code > Download ZIP
- Follow the instructions (without seeding)
- Launch the app with `npm start`

![image](https://github.com/casejs/CASE/assets/6626184/00bdf515-d4ee-47d8-9f15-fc849eb9a4da)

**Comment by Tjs002** [comment]
@brunobuddy I was trying to solve this can u tell me how did u check for the values in the DB(function for checking the values), bcoz I can see that the values for email and password were hard-coded?

**Comment by Tjs002** [comment]
@brunobuddy and @SebConejo I have raised PR #102 you can check it and let me know if it's the solution u wanted.
